### Soni Kevin Harshadbhai

### MScit Sem-2

### Sub= MLP

### Enrollment:2024008190100

In [5]:
import numpy as np # np is not mandatory

In [6]:
#Function

In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
#shape function of array 2 row and 3 columns
print(f"shape of a{format(a.shape)}")
#2dim or 1 dim
print(f"Number of dimension{format(a.ndim)}")
#array of size
print(f"size of array{format(a.size)}")
#Itemsize show  the size of each element like how many memory they occupie
print(f"Itemsize{(a.itemsize)}")
#data function is shows the location of the data
print(f"data{a.data}")

shape of a(2, 3)
Number of dimension2
size of array6
Itemsize8
data<memory at 0x0000021339EB12F0>


In [9]:
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[9,8,7],[44,55,66]])
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]]
[[ 9  8  7]
 [44 55 66]]


In [10]:
# in this array start with 0 in 3 means all element or 1 row show mate & 2 coloum show kare
sliceArr = m1[:1]
print(sliceArr)

[[1 2 3]]


In [11]:
sliceArr = m1[:2]
print(sliceArr)

[[1 2 3]
 [4 5 6]]


In [12]:
sliceArr = m1[:3,:2]
print(sliceArr)

[[1 2]
 [4 5]]


In [13]:
print (m1.sum())

21


In [14]:
m3=np.array([[1,2],[5,6]])
m4=np.array([[9,8],[55,66]])
print(m3)
print(m4)

[[1 2]
 [5 6]]
[[ 9  8]
 [55 66]]


In [15]:
mul=np.dot(m3,m4)
print(mul)

[[119 140]
 [375 436]]


In [16]:
mulM=np.multiply(m3,m4)
print(mulM)

[[  9  16]
 [275 396]]


In [17]:
subM=np.subtract(m4,m3)
print(subM)

[[ 8  6]
 [50 60]]


In [21]:
m5=np.array([1,2,3,4,5,6,7,8])
print(m5)
reshpe=m5.reshape(2,4)#resize the array if your value is 10 than 2,5 value you can resize not 6,4
print(reshpe)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [22]:
print(m5.max())

8


In [23]:
print(m5.min())

1


In [24]:
print(reshpe.max(axis=1))

[4 8]


In [26]:
print(reshpe.min(axis=0))

[1 2 3 4]


In [27]:
m6= np.array([[3,11,26],[25,45,56]])
print(m6)
print(np.std(m6))

[[ 3 11 26]
 [25 45 56]]
18.254375426790755


In [29]:
v=np.vstack((m1,m2))
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 9  8  7]
 [44 55 66]]


In [30]:
h=np.hstack((m1,m2))
print(h)

[[ 1  2  3  9  8  7]
 [ 4  5  6 44 55 66]]


In [32]:
arry= np.arange(0,20,2,float)
print(arry)
print(arry.dtype)

[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
float64


In [34]:
arry1= np.linspace(0,20,2)
print(arry1)

[ 0. 20.]


In [35]:
arry1= np.linspace(0,20,10)
print(arry1)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [36]:
ht= h.T
print(ht)

[[ 1  4]
 [ 2  5]
 [ 3  6]
 [ 9 44]
 [ 8 55]
 [ 7 66]]


In [39]:
for i in np.nditer(ht):
    print("ele:",i)

ele: 1
ele: 2
ele: 3
ele: 9
ele: 8
ele: 7
ele: 4
ele: 5
ele: 6
ele: 44
ele: 55
ele: 66


In [40]:
print(np.hsplit(h,2))

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 9,  8,  7],
       [44, 55, 66]])]


In [42]:
print(np.vsplit(h,2))

[array([[1, 2, 3, 9, 8, 7]]), array([[ 4,  5,  6, 44, 55, 66]])]


SONI Kevin